// Date: 2/9/17 16:09:13
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX
package erikalebenjamattias.petrimod.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelGrandPiano extends ModelBase {
	public ModelRenderer frontPanel;
	public ModelRenderer keyPanel;
	public ModelRenderer keyPanelWallLeft;
	public ModelRenderer keyPanelWallRight;
	public ModelRenderer rightPanel;
	public ModelRenderer leftPanel;
	public ModelRenderer backPanel;
	public ModelRenderer indentRearPanel;
	public ModelRenderer indentFrontPanel;
	public ModelRenderer keys;
	public ModelRenderer bottomPanel;
	public ModelRenderer inside;
	public ModelRenderer lid;
	public ModelRenderer leftLeg;
	public ModelRenderer rightLeg;
	public ModelRenderer rearLeg;
	public ModelRenderer lidSupportStick;
	public ModelRenderer pedalHolder;
	public ModelRenderer leftPedal;
	public ModelRenderer rightPedal;

	public ModelGrandPiano() {
		textureWidth = 128;
		textureHeight = 128;

		frontPanel = new ModelRenderer(this, 0, 0);
		frontPanel.addBox(-11F, 0F, 0F, 22, 6, 1);
		frontPanel.setRotationPoint(0F, 9F, -11F);
		frontPanel.setTextureSize(64, 32);
		frontPanel.mirror = true;
		setRotation(frontPanel, 0F, 0F, 0F);
		keyPanel = new ModelRenderer(this, 0, 7);
		keyPanel.addBox(-10F, 0F, -3F, 20, 1, 4);
		keyPanel.setRotationPoint(0F, 15F, -11F);
		keyPanel.setTextureSize(64, 32);
		keyPanel.mirror = true;
		setRotation(keyPanel, 0F, 0F, 0F);
		keyPanelWallLeft = new ModelRenderer(this, 48, 13);
		keyPanelWallLeft.addBox(0F, 0F, -3F, 1, 2, 11);
		keyPanelWallLeft.setRotationPoint(10F, 14F, -11F);
		keyPanelWallLeft.setTextureSize(64, 32);
		keyPanelWallLeft.mirror = true;
		setRotation(keyPanelWallLeft, 0F, 0F, 0F);
		keyPanelWallRight = new ModelRenderer(this, 48, 0);
		keyPanelWallRight.addBox(-1F, 0F, -3F, 1, 2, 11);
		keyPanelWallRight.setRotationPoint(-10F, 14F, -11F);
		keyPanelWallRight.setTextureSize(64, 32);
		keyPanelWallRight.mirror = true;
		setRotation(keyPanelWallRight, 0F, 0F, 0F);
		rightPanel = new ModelRenderer(this, 82, 0);
		rightPanel.addBox(-1F, 0F, 0F, 1, 6, 22);
		rightPanel.setRotationPoint(-10F, 9F, -10F);
		rightPanel.setTextureSize(64, 32);
		rightPanel.mirror = true;
		setRotation(rightPanel, 0F, 0F, 0F);
		leftPanel = new ModelRenderer(this, 0, 12);
		leftPanel.addBox(0F, 0F, 0F, 1, 6, 8);
		leftPanel.setRotationPoint(10F, 9F, -10F);
		leftPanel.setTextureSize(64, 32);
		leftPanel.mirror = true;
		setRotation(leftPanel, 0F, 0F, 0F);
		backPanel = new ModelRenderer(this, 18, 19);
		backPanel.addBox(-6F, 0F, 0F, 12, 6, 1);
		backPanel.setRotationPoint(-4F, 9F, 12F);
		backPanel.setTextureSize(64, 32);
		backPanel.mirror = true;
		setRotation(backPanel, 0F, 0F, 0F);
		indentRearPanel = new ModelRenderer(this, 0, 26);
		indentRearPanel.addBox(-1F, 0F, -13F, 1, 6, 13);
		indentRearPanel.setRotationPoint(2F, 9F, 13F);
		indentRearPanel.setTextureSize(64, 32);
		indentRearPanel.mirror = true;
		setRotation(indentRearPanel, 0F, -0.2486148F, 0F);
		indentFrontPanel = new ModelRenderer(this, 18, 12);
		indentFrontPanel.addBox(-7F, 0F, -1F, 7, 6, 1);
		indentFrontPanel.setRotationPoint(11F, 9F, -2F);
		indentFrontPanel.setTextureSize(64, 32);
		indentFrontPanel.mirror = true;
		setRotation(indentFrontPanel, 0F, 0.4519611F, 0F);
		keys = new ModelRenderer(this, 28, 26);
		keys.addBox(-10F, 0F, -3F, 20, 1, 3);
		keys.setRotationPoint(0F, 14.5F, -10.5F);
		keys.setTextureSize(64, 32);
		keys.mirror = true;
		setRotation(keys, 0F, 0F, 0F);
		bottomPanel = new ModelRenderer(this, 66, 28);
		bottomPanel.addBox(-10F, 0F, 0F, 20, 0, 22);
		bottomPanel.setRotationPoint(0F, 14.5F, -10F);
		bottomPanel.setTextureSize(64, 32);
		bottomPanel.mirror = true;
		setRotation(bottomPanel, 0F, 0F, 0F);
		inside = new ModelRenderer(this, 86, 50);
		inside.addBox(-10F, 0F, 0F, 20, 0, 22);
		inside.setRotationPoint(0F, 10.5F, -10F);
		inside.setTextureSize(64, 32);
		inside.mirror = true;
		setRotation(inside, 0F, 0F, 0F);
		lid = new ModelRenderer(this, 60, 72);
		lid.addBox(0F, 0F, -12F, 22, 0, 24);
		lid.setRotationPoint(-11F, 8.9F, 1F);
		lid.setTextureSize(64, 32);
		lid.mirror = true;
		setRotation(lid, 0F, 0F, -0.443034918F);
		leftLeg = new ModelRenderer(this, 0, 45);
		leftLeg.addBox(-1F, 0F, -1F, 2, 10, 2);
		leftLeg.setRotationPoint(9F, 14F, -8F);
		leftLeg.setTextureSize(64, 32);
		leftLeg.mirror = true;
		setRotation(leftLeg, 0F, 0F, 0F);
		rightLeg = new ModelRenderer(this, 0, 45);
		rightLeg.addBox(-1F, 0F, -1F, 2, 10, 2);
		rightLeg.setRotationPoint(-9F, 14F, -8F);
		rightLeg.setTextureSize(64, 32);
		rightLeg.mirror = true;
		setRotation(rightLeg, 0F, 0F, 0F);
		rearLeg = new ModelRenderer(this, 0, 45);
		rearLeg.addBox(0F, 0F, 0F, 2, 10, 2);
		rearLeg.setRotationPoint(-5F, 14F, 10F);
		rearLeg.setTextureSize(64, 32);
		rearLeg.mirror = true;
		setRotation(rearLeg, 0F, 0F, 0F);
		lidSupportStick = new ModelRenderer(this, 72, 0);
		lidSupportStick.addBox(-1F, -10F, 0F, 1, 11, 1);
		lidSupportStick.setRotationPoint(10F, 10F, -4F);
		lidSupportStick.setTextureSize(64, 32);
		lidSupportStick.mirror = true;
		setRotation(lidSupportStick, 0F, 0F, -0.4537856F);
		pedalHolder = new ModelRenderer(this, 72, 12);
		pedalHolder.addBox(-2F, 0F, 0F, 4, 8, 0);
		pedalHolder.setRotationPoint(0F, 14F, -8F);
		pedalHolder.setTextureSize(64, 32);
		pedalHolder.mirror = true;
		setRotation(pedalHolder, 0F, 0F, 0F);
		leftPedal = new ModelRenderer(this, 74, 0);
		leftPedal.addBox(0F, 0F, -2F, 1, 0, 2);
		leftPedal.setRotationPoint(1F, 22F, -8F);
		leftPedal.setTextureSize(64, 32);
		leftPedal.mirror = true;
		setRotation(leftPedal, 0F, 0F, 0F);
		rightPedal = new ModelRenderer(this, 74, 0);
		rightPedal.addBox(-1F, 0F, -2F, 1, 0, 2);
		rightPedal.setRotationPoint(-1F, 22F, -8F);
		rightPedal.setTextureSize(64, 32);
		rightPedal.mirror = true;
		setRotation(rightPedal, 0F, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		frontPanel.render(f5);
		keyPanel.render(f5);
		keyPanelWallLeft.render(f5);
		keyPanelWallRight.render(f5);
		rightPanel.render(f5);
		leftPanel.render(f5);
		backPanel.render(f5);
		indentRearPanel.render(f5);
		indentFrontPanel.render(f5);
		keys.render(f5);
		bottomPanel.render(f5);
		inside.render(f5);
		lid.render(f5);
		leftLeg.render(f5);
		rightLeg.render(f5);
		rearLeg.render(f5);
		lidSupportStick.render(f5);
		pedalHolder.render(f5);
		leftPedal.render(f5);
		rightPedal.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}

}
